version: "2.1"
orbs:
  <orb-name>: <namespace>/<orb-name>@x.y.z
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
 
