version: "2.1"
orbs:
  cypress: cypress-io/cypress@3
jobs:
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/
  run-tests-in-parallel:
    executor: cypress/default
    parallelism: 1
    steps:
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          cypress-command: npx cypress run
workflows:
  use-my-orb:
    jobs:
      - install-and-persist:
          name: Install & Persist To Workspace
      - run-tests-in-parallel:
          name: Run Tests
          requires:
            - Install & Persist To Workspace
      - store-reports:
          name: Store Reports
          when: always
          requires:
            - Run Tests
          steps:
            - persist_to_workspace:
                paths:
                  - cypress/reports
                root: ~/
            - store_artifacts:
                path: cypress/reports
