version: "2.1"
orbs:
  cypress: cypress-io/cypress@3
  mochawesome: cypress-io/mochawesome@1

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          parallel: true
          record: true
          # Additional configuration for Mochawesome reports
          post-steps:
            - mochawesome/generate:
                format: "json"
                outputDir: "cypress/results/mochawesome"
  