version: "2.1"
orbs:
  cypress: cypress-io/cypress@3

jobs:
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/

  run-tests-in-parallel:
    executor: cypress/default
    parallelism: 1
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Tests with Mochawesome Reporter
          command: |
            npx cypress run --reporter mochawesome

  store-reports:
    docker:
      - image: cypress/base:10
    steps:
      - attach_workspace:
          at: ~/
      - persist_to_workspace:
          paths:
            - cypress/reports
          root: ~/

workflows:
  use-my-orb:
    jobs:
      - install-and-persist:
          name: Install & Persist To Workspace

      - run-tests-in-parallel:
          name: Run Tests
          requires:
            - Install & Persist To Workspace

      - store-reports:
          name: Store Reports
          requires:
            - Run Tests
