version: "2.1"

orbs:
  cypress: cypress-io/cypress@3

jobs:
  install-and-run-tests:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - cypress/run:
          command: npx cypress run --reporter mochawesome

  store-reports:
    docker:
      - image: cypress/base:latest
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: Generate Mocha Reports
          command: |
            npx mochawesome-merge --reportDir cypress/reports/html --reportFilename mochawesome.json > merged-report.json
            npx mochawesome-report-generator --reportDir cypress/reports/html --reportFilename mochawesome.json --reportTitle "Custom Title"
            cp -r cypress/videos cypress/reports/html/videos

      - persist_to_workspace:
          paths:
            - cypress/reports
          root: /root/project

workflows:
  version: 2
  use-my-orb:
    jobs:
      - install-and-run-tests
      - store-reports:
          requires:
            - install-and-run-tests
