name: Chrome
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - name: Run Cypress tests
        run: |
          npm install # Ensure necessary packages are installed
          npx cypress run # Adjust the script based on your project setup
      - name: Generate Mocha report
        run: |
          npm install mocha-multi-reporters
          npx mocha --reporter mocha-multi-reporters --reporter-options configFile=config/mocha-reporter-config.json # Adjust the path and config file based on your project setup
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        with:
          name: mocha-report
          path: mochareports # Adjust the path based on your project setup
          if-no-files-found: ignore
